### ISSUE TITLE
Similar extension de.systopia.recentitems

### ISSUE THREAD

**Issue by jensschuppe** [civicrm/org.civicrm.recentmenu#1]
We released a similar extension here: https://github.com/systopia/de.systopia.recentitems.

We took a different approach to avoid menu rebuilds for each change of recent items. Instead, the updated recent items menu is injected using an Ajax API call, with the main navigation menu holding only a placeholder ("Loading").

Also, we tried to keep core icons and added some styling support for Shoreditch.

Maybe there's a chance for merging the extensions, or at least discussing advantages and downsides of each approach ...?

**Comment by colemanw** [comment]
Hi @jensschuppe thanks for flagging this. I agree there is overlap and the 2 extensions should be combined into one.

IMO What we need is a core patch which provides an interface adding/removing menu items on-the-fly via JS, for extensions like this one and for https://github.com/civicrm/org.civicrm.tutorial which needs to show/hide/add/remove items from the menubar and currently does so with some ugly jQuery hacks. Adding such an abstraction layer to core would be a nice future-proof way to eventually use a different js library for the menubar.

Also, as nice as your new api is, I think it would be more efficient to push that data into the dom on page load to avoid the extra ajax overhead.

FYI the bootstrap icons are now part of core and not needed in your extension. See https://github.com/civicrm/org.civicrm.shoreditch/pull/255

**Comment by colemanw** [comment]
@jensschuppe I've opened an issue for the `CRM.menubar` abstraction layer (with a bit more ambitious scope): https://lab.civicrm.org/dev/core/issues/487

**Comment by colemanw** [comment]
https://github.com/systopia/de.systopia.recentitems/issues/3
