### ISSUE TITLE
Recent menu does not show on non-parent domain on multisite

### ISSUE THREAD

**Issue by andyburnsco** [civicrm/org.civicrm.recentmenu#13]
Upgraded from 1.3 to 1.5 on Civi 5.50.0 on WP. Recent menu item no longer inserted into navigation table on non parent domain sites.

Looks like this is the change that did it https://github.com/civicrm/org.civicrm.recentmenu/commit/01ff2bcae4283ec36cb06a409be7e43059e16ad6.

**Comment by colemanw** [comment]
Interesting. I'd always wondered how managed entities work on multi-site systems. I guess the answer is, they don't!

**Comment by andyburnsco** [comment]
Yeah, I actually prefer the prior approach because it is easier to manage a global multisite site system and standardize. Otherwise, you end up needing to do mysql updates to `civicrm_navigation` to apply a uniform approach (just in general with the nav).

**Comment by colemanw** [comment]
@andyburnsco can you try this patch? #14

**Comment by andyburnsco** [comment]
I applied the patch, disabled and re-enabled extension, cleared cache and still remains only on parent site. `civicrm_navigation` shows

![image](https://user-images.githubusercontent.com/18341942/171484345-1bb4947e-3220-4366-af68-6b00c023c8fe.png)

**Comment by colemanw** [comment]
@andyburnsco can you clear caches?

**Comment by andyburnsco** [comment]
> @andyburnsco can you clear caches?

I did on each domain.

**Comment by colemanw** [comment]
Ok, and what do you see in your `civicrm_managed` table when you do this:

`SELECT * FROM civicrm_managed WHERE module = 'org.civicrm.recentmenu'`

**Comment by colemanw** [comment]
Ok, and what do you see in your `civicrm_managed` table when you do this:

`SELECT * FROM civicrm_managed WHERE module = 'org.civicrm.recentmenu'`

**Comment by andyburnsco** [comment]
> Ok, and what do you see in your `civicrm_managed` table when you do this:
> 
> `SELECT * FROM civicrm_managed WHERE module = 'org.civicrm.recentmenu'`

![image](https://user-images.githubusercontent.com/18341942/171501364-dc5c27b7-da7d-45d8-b0e5-b2d510528cc8.png)

**Comment by colemanw** [comment]
Strange. The .mgd file is supposed to return one per active domain. What do you see in the `civicrm_domain` table?

**Comment by andyburnsco** [comment]
We have 59 domains setup all using 5.50.0

**Comment by colemanw** [comment]
Aha. The `is_active` condition was messing it up. I've updated the PR and I think it will work now.

**Comment by andyburnsco** [comment]
Working, `civicrm_managed` and `civicrm_navigiation` have the 59 domain entries.

**Comment by colemanw** [comment]
Great thanks for testing @andyburnsco

**Comment by colemanw** [comment]
@andyburnsco while we're on the subject... do you use SearchKit? Did you notice the same problem with the SearchKit menu only being added for the first domain and not any others?
I've just added the same type of .mgd.php approach to fix the SearchKit menu: https://github.com/civicrm/civicrm-core/pull/23670 but I'm curious to know why no one complained about it previously.

**Comment by andyburnsco** [comment]
Yes, using Search Kit and it currently only shows on parent domain.  Same issue here. 

Note, it is accessible if you go to the URL on a sub site replacing the domain. I'll test that out and comment there soon.

**Comment by colemanw** [comment]
Good to know, thanks @andyburnsco for testing out that other PR.
