### ISSUE TITLE
Menu Language Change

### ISSUE THREAD

**Issue by fatihates24** [civicrm/org.civicrm.recentmenu#16]
Hello, I am using CiviCRM in Turkish. When I installed the Recent Menu extension, the button on the menu appeared in English. I want to change the menu title, what can I do for this?

**Comment by colemanw** [comment]
According to the stats on Transifex, this should already be translated. See https://explore.transifex.com/civicrm/civicrm_extensions/
Did you download the [Uplang extension](https://lab.civicrm.org/extensions/uplang)?

But you can still change the label of any menu item in your install by going here:
![image](https://github.com/civicrm/org.civicrm.recentmenu/assets/2874912/0e04166b-7ee2-4e41-a72e-76d42bce45ca)

**Comment by fatihates24** [comment]
I hadn't even thought about making the change through "Navigation Menu." Thank you for your interest. The currently installed version of Joomla! is 4.3.4, and it's currently working flawlessly for CiviCRM 5.64.1.

**Comment by mlutfy** [comment]
I double-checked and it took a while, but it eventually worked:

![image](https://github.com/civicrm/org.civicrm.recentmenu/assets/254741/f73654d0-a929-44fc-9b09-2948d4ea93fd)

I tested on a demo site:

- Enabled the "update language" (or "uplang") extension https://civicrm.org/extensions/update-language-files
- Enabled the "recent items"
- Set the default language to Turkish

The menu system only supports one language, so if you have multiple languages enabled, it will set the menu title to the language of the interface when the menu cache is rebuilt. I had to go to Administer > System Settings > Cleanup Caches, for the translation to be effective.
