### ISSUE TITLE
Is there a chance this extension would work without KAM?

### ISSUE THREAD

**Issue by tapashdatta** [civicrm/org.civicrm.recentmenu#2]
After installing this extension with KAM, shoreditch theme style messes up because of KAM. Is there a way to enable this extension without KAM? Thanks

**Comment by mlutfy** [comment]
Hi @tapashdatta, there is a patch available for Shoreditch: https://github.com/civicrm/org.civicrm.shoreditch/pull/364

KAM is the menu as of CiviCRM 5.12, so hopefull shoreditch will merge the PR in time.

**Comment by colemanw** [comment]
@tapashdatta you can use v1.0 of this extension without KAM.
