### ISSUE TITLE
Insert the 'recent items' menu at the left side of the menu

### ISSUE THREAD

**Issue by bjendres** [civicrm/org.civicrm.recentmenu#6]
It's an easy patch to achieve that, just change [this](https://github.com/civicrm/org.civicrm.recentmenu/blob/b09c7cd73629c49a3507d8d00bbd05af5fcf7144/js/recentmenu.js#L5) line from
``
CRM.menubar.addItems(-1, null, [CRM.vars.recentmenu]);
``
to
``
CRM.menubar.addItems(1, null, [CRM.vars.recentmenu]);
``

However, it would be nice to have that as a config option. I'm just sharing the patch, but maybe somebody will implement it as on option.

**Comment by colemanw** [comment]
How about we do this and allow the admin to customize the menu however they wish: #9
Can you please review that PR @bjendres
